set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,euc-jp,iso-2022-jp,ucs-2le,ucs-2,cp932

set expandtab tabstop=2 shiftwidth=2 softtabstop=2
set laststatus=2

set noautoindent
set nosmartindent

syntax on
set background=dark

set hlsearch
set showmatch
set ignorecase

set noswapfile
set ambiwidth=double

set modeline

"for Select&Search
vnoremap <silent> * "vy/\V<C-r>=substitute(escape(@v,'\/'),"\n",'\\n','g')<CR><CR>
