set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,euc-jp,iso-2022-jp,ucs-2le,ucs-2,cp932

set expandtab tabstop=2 shiftwidth=2 softtabstop=2
set statusline=%f%m%r%w%=[COL:\ %03v][ROW:\ %l/%L]
set laststatus=2

set noautoindent
set nosmartindent

syntax on
set background=dark

set hlsearch
set showmatch

set noswapfile
set ambiwidth=double


set modeline

"for Select&Search
vnoremap <silent> * "vy/\V<C-r>=substitute(escape(@v,'\/'),"\n",'\\n','g')<CR><CR>

"Dictionary
autocmd FileType php,ctp :set dictionary=~/.vim/dict/php.dict

" Updated Syntax for PHP-7
" https://raw.githubusercontent.com/StanAngeloff/php.vim/master/syntax/php.vim
" @place .vim/after/syntax/php7.vim
au BufRead,BufNewFile *.php set filetype=php7
au BufRead,BufNewFile *.blade.php set filetype=blade

"for Binary Mode
augroup BinaryXXD
  autocmd!
  autocmd BufReadPre  *.bin let &binary =1
  autocmd BufReadPost * if &binary | silent %!xxd -g 1
  autocmd BufReadPost * set ft=xxd | endif
  autocmd BufWritePre * if &binary | %!xxd -r | endif
  autocmd BufWritePost * if &binary | silent %!xxd -g 1
  autocmd BufWritePost * set nomod | endif
augroup END

